### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by JetSetIlly** [mslinklater/retrotools#31]
Using cmake 3.16.2

CMake Error at CMakeLists.txt:46 (add_subdirectory):
  add_subdirectory given source "shared_cpp" which is not an existing
  directory.

**Comment by mslinklater** [comment]
Ah, yes, you need to put the code in my 'shared_cpp' repo in there. I need to write some proper build instructions 8). What I do is have shared_cpp next to retrotools and then symlink the folder in. Thanks for the feedback !

**Comment by mslinklater** [comment]
I've added a few notes to the build instructions... closing this for now.
