### ISSUE TITLE
NTSC/PAL/SECAM Selection

### ISSUE THREAD

**Issue by mslinklater** [mslinklater/retrotools#41]
Global tick counts
Palette

**Comment by JetSetIlly** [comment]
I've not studied your code yet but how have you decided to implement this? I've never been very happy with my method.

**Comment by mslinklater** [comment]
I store the video buffer as palette index values and then when I build the RGBA texture for OpenGL to use I reference whichever palette I want to use. 

Look at windows/tiawindow.cpp, lines 284-361.

**Comment by JetSetIlly** [comment]
Fair play. Have you thought about how the code can decide on its own whether to use PAL or NTSC? I thought counting active scanlines would work. It does work in many cases but there are some false positives.
